import { useEffect, useState } from 'react';
import { Filter, MapPin, Search, ShoppingBag, Sparkles, Tag } from 'lucide-react';
import Card from '../ui/Card';
import Button from '../ui/Button';
import { getListings, placeOrder } from '../../services/marketplace.service';
import { INDIAN_STATES, WOOL_TYPES } from '../../constants/states';

export default function MarketplaceExperience({ allowBuying = false }) {
  const [listings, setListings] = useState([]); const [loading, setLoading] = useState(true); const [search, setSearch] = useState(''); const [state, setState] = useState(''); const [woolType, setWoolType] = useState(''); const [buyingId, setBuyingId] = useState(null); const [message, setMessage] = useState('');
  const load = async () => { setLoading(true); const result = await getListings({ state: state || undefined, woolType: woolType || undefined, search: search || undefined }); setListings(result.data || []); setLoading(false); };
  useEffect(() => { load(); }, [state, woolType]); useEffect(() => { const timer = setTimeout(load, 350); return () => clearTimeout(timer); }, [search]);
  const buy = async (listingId) => { setBuyingId(listingId); setMessage(''); const { error } = await placeOrder({ listingId }); setBuyingId(null); setMessage(error ? error.message : 'Your 1 kg order has been placed successfully.'); if (!error) load(); };
  return <main className="page-shell marketplace-page"><section className="market-hero animate-enter"><div><p className="eyebrow"><Sparkles size={14}/> Direct from verified producers</p><h1>Find wool with a <em>proven story.</em></h1><p>Discover traceable lots from growers and cooperatives across India.</p></div><Tag className="market-hero-icon" size={100}/></section><section className="market-controls animate-enter delay-1"><div className="search-field"><Search size={18}/><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search wool, state or producer"/></div><div className="filter-row"><span><Filter size={15}/> Filter</span><select value={state} onChange={event => setState(event.target.value)}><option value="">All states</option>{INDIAN_STATES.map(item => <option key={item.code} value={item.name}>{item.name}</option>)}</select><select value={woolType} onChange={event => setWoolType(event.target.value)}><option value="">All wool types</option>{WOOL_TYPES.map(item => <option key={item} value={item}>{item}</option>)}</select></div></section>{message && <p className="market-message">{message}</p>}<section className="mt-7"><div className="section-heading"><div><p className="eyebrow text-primary"><ShoppingBag size={14}/> Available today</p><h2>{loading ? 'Finding the best lots…' : `${listings.length} wool lots available`}</h2></div></div>{loading ? <div className="loader-stage"><div className="h-9 w-9 animate-spin rounded-full border-2 border-primary border-t-transparent"/></div> : listings.length === 0 ? <Card className="empty-state"><Search size={28}/><h3>No wool lots found</h3><p>Try a different search or remove a filter to discover more lots.</p></Card> : <div className="listing-grid">{listings.map(listing => <Card key={listing.id} className="listing-card group"><div className="listing-image"><img src={listing.image_url || 'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800&auto=format&fit=crop&q=70'} alt={listing.wool_type}/><span>{listing.quantity_kg} kg available</span></div><div className="pt-4"><div className="flex items-start justify-between gap-3"><div><h3>{listing.wool_type} wool</h3><p className="listing-location"><MapPin size={13}/>{listing.district}, {listing.state}</p></div><strong>₹{listing.price_per_kg}<small>/kg</small></strong></div><p className="mt-3 text-xs text-textSecondary">From {listing.seller_name || 'a verified producer'}</p>{allowBuying && <Button title="Order 1 kg" icon={ShoppingBag} loading={buyingId === listing.id} onClick={() => buy(listing.id)} className="mt-4"/>}</div></Card>)}</div>}</section></main>;
}
